# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/a7-35t.xdc

# XDC: new/master.xdc

# Block Designs: bd/QCS_4/QCS_4.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4 || ORIG_REF_NAME==QCS_4} -quiet] -quiet

# IP: bd/QCS_4/ip/QCS_4_rpm_lut_0_0/QCS_4_rpm_lut_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_rpm_lut_0_0 || ORIG_REF_NAME==QCS_4_rpm_lut_0_0} -quiet] -quiet

# IP: bd/QCS_4/ip/QCS_4_clk_cascade_0_0/QCS_4_clk_cascade_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_clk_cascade_0_0 || ORIG_REF_NAME==QCS_4_clk_cascade_0_0} -quiet] -quiet

# IP: bd/QCS_4/ip/QCS_4_addr_mux_0_0/QCS_4_addr_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_addr_mux_0_0 || ORIG_REF_NAME==QCS_4_addr_mux_0_0} -quiet] -quiet

# IP: bd/QCS_4/ip/QCS_4_QCS_no_lut_0_0/QCS_4_QCS_no_lut_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_QCS_no_lut_0_0 || ORIG_REF_NAME==QCS_4_QCS_no_lut_0_0} -quiet] -quiet

# IP: bd/QCS_4/ip/QCS_4_QCS_no_lut_1_0/QCS_4_QCS_no_lut_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_QCS_no_lut_1_0 || ORIG_REF_NAME==QCS_4_QCS_no_lut_1_0} -quiet] -quiet

# IP: bd/QCS_4/ip/QCS_4_QCS_no_lut_2_0/QCS_4_QCS_no_lut_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_QCS_no_lut_2_0 || ORIG_REF_NAME==QCS_4_QCS_no_lut_2_0} -quiet] -quiet

# IP: bd/QCS_4/ip/QCS_4_QCS_no_lut_3_0/QCS_4_QCS_no_lut_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_QCS_no_lut_3_0 || ORIG_REF_NAME==QCS_4_QCS_no_lut_3_0} -quiet] -quiet

# Block Designs: bd/QCS_4_Top/QCS_4_Top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top || ORIG_REF_NAME==QCS_4_Top} -quiet] -quiet

# IP: bd/QCS_4_Top/ip/QCS_4_Top_QCS_4_wrapper_0_0/QCS_4_Top_QCS_4_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top_QCS_4_wrapper_0_0 || ORIG_REF_NAME==QCS_4_Top_QCS_4_wrapper_0_0} -quiet] -quiet

# Block Designs: bd/QCS_4/QCS_4.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4 || ORIG_REF_NAME==QCS_4} -quiet] -quiet

# IP: bd/QCS_4/ip/QCS_4_rpm_lut_0_0/QCS_4_rpm_lut_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_rpm_lut_0_0 || ORIG_REF_NAME==QCS_4_rpm_lut_0_0} -quiet] -quiet

# IP: bd/QCS_4/ip/QCS_4_clk_cascade_0_0/QCS_4_clk_cascade_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_clk_cascade_0_0 || ORIG_REF_NAME==QCS_4_clk_cascade_0_0} -quiet] -quiet

# IP: bd/QCS_4/ip/QCS_4_addr_mux_0_0/QCS_4_addr_mux_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_addr_mux_0_0 || ORIG_REF_NAME==QCS_4_addr_mux_0_0} -quiet] -quiet

# IP: bd/QCS_4/ip/QCS_4_QCS_no_lut_0_0/QCS_4_QCS_no_lut_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_QCS_no_lut_0_0 || ORIG_REF_NAME==QCS_4_QCS_no_lut_0_0} -quiet] -quiet

# IP: bd/QCS_4/ip/QCS_4_QCS_no_lut_1_0/QCS_4_QCS_no_lut_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_QCS_no_lut_1_0 || ORIG_REF_NAME==QCS_4_QCS_no_lut_1_0} -quiet] -quiet

# IP: bd/QCS_4/ip/QCS_4_QCS_no_lut_2_0/QCS_4_QCS_no_lut_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_QCS_no_lut_2_0 || ORIG_REF_NAME==QCS_4_QCS_no_lut_2_0} -quiet] -quiet

# IP: bd/QCS_4/ip/QCS_4_QCS_no_lut_3_0/QCS_4_QCS_no_lut_3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_QCS_no_lut_3_0 || ORIG_REF_NAME==QCS_4_QCS_no_lut_3_0} -quiet] -quiet

# IP: bd/QCS_4_Top/ip/QCS_4_Top_clk_wiz_0_0/QCS_4_Top_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top_clk_wiz_0_0 || ORIG_REF_NAME==QCS_4_Top_clk_wiz_0_0} -quiet] -quiet

# IP: bd/QCS_4_Top/ip/QCS_4_Top_encoding_sequencer_0_0/QCS_4_Top_encoding_sequencer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top_encoding_sequencer_0_0 || ORIG_REF_NAME==QCS_4_Top_encoding_sequencer_0_0} -quiet] -quiet

# IP: bd/QCS_4_Top/ip/QCS_4_Top_encoding_sequencer_1_0/QCS_4_Top_encoding_sequencer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top_encoding_sequencer_1_0 || ORIG_REF_NAME==QCS_4_Top_encoding_sequencer_1_0} -quiet] -quiet

# IP: bd/QCS_4_Top/ip/QCS_4_Top_encoding_sequencer_2_0/QCS_4_Top_encoding_sequencer_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top_encoding_sequencer_2_0 || ORIG_REF_NAME==QCS_4_Top_encoding_sequencer_2_0} -quiet] -quiet

# IP: bd/QCS_4_Top/ip/QCS_4_Top_encoding_sequencer_3_0/QCS_4_Top_encoding_sequencer_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top_encoding_sequencer_3_0 || ORIG_REF_NAME==QCS_4_Top_encoding_sequencer_3_0} -quiet] -quiet

# IP: bd/QCS_4_Top/ip/QCS_4_Top_microblaze_0_0/QCS_4_Top_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top_microblaze_0_0 || ORIG_REF_NAME==QCS_4_Top_microblaze_0_0} -quiet] -quiet

# IP: bd/QCS_4_Top/ip/QCS_4_Top_dlmb_v10_0/QCS_4_Top_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top_dlmb_v10_0 || ORIG_REF_NAME==QCS_4_Top_dlmb_v10_0} -quiet] -quiet

# IP: bd/QCS_4_Top/ip/QCS_4_Top_ilmb_v10_0/QCS_4_Top_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top_ilmb_v10_0 || ORIG_REF_NAME==QCS_4_Top_ilmb_v10_0} -quiet] -quiet

# IP: bd/QCS_4_Top/ip/QCS_4_Top_dlmb_bram_if_cntlr_0/QCS_4_Top_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==QCS_4_Top_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/QCS_4_Top/ip/QCS_4_Top_ilmb_bram_if_cntlr_0/QCS_4_Top_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==QCS_4_Top_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/QCS_4_Top/ip/QCS_4_Top_lmb_bram_0/QCS_4_Top_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top_lmb_bram_0 || ORIG_REF_NAME==QCS_4_Top_lmb_bram_0} -quiet] -quiet

# IP: bd/QCS_4_Top/ip/QCS_4_Top_xbar_0/QCS_4_Top_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top_xbar_0 || ORIG_REF_NAME==QCS_4_Top_xbar_0} -quiet] -quiet

# IP: bd/QCS_4_Top/ip/QCS_4_Top_microblaze_0_axi_periph_0/QCS_4_Top_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top_microblaze_0_axi_periph_0 || ORIG_REF_NAME==QCS_4_Top_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/QCS_4_Top/ip/QCS_4_Top_microblaze_0_axi_intc_0/QCS_4_Top_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top_microblaze_0_axi_intc_0 || ORIG_REF_NAME==QCS_4_Top_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/QCS_4_Top/ip/QCS_4_Top_microblaze_0_xlconcat_0/QCS_4_Top_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top_microblaze_0_xlconcat_0 || ORIG_REF_NAME==QCS_4_Top_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/QCS_4_Top/ip/QCS_4_Top_mdm_1_0/QCS_4_Top_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top_mdm_1_0 || ORIG_REF_NAME==QCS_4_Top_mdm_1_0} -quiet] -quiet

# IP: bd/QCS_4_Top/ip/QCS_4_Top_rst_clk_wiz_0_100M_0/QCS_4_Top_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==QCS_4_Top_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/QCS_4_Top/ip/QCS_4_Top_axi_uartlite_0_0/QCS_4_Top_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top_axi_uartlite_0_0 || ORIG_REF_NAME==QCS_4_Top_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/QCS_4_Top/ip/QCS_4_Top_QCS_4_AXI_0_0/QCS_4_Top_QCS_4_AXI_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top_QCS_4_AXI_0_0 || ORIG_REF_NAME==QCS_4_Top_QCS_4_AXI_0_0} -quiet] -quiet

# IP: bd/QCS_4_Top/ip/QCS_4_Top_ila_0_0/QCS_4_Top_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_Top_ila_0_0 || ORIG_REF_NAME==QCS_4_Top_ila_0_0} -quiet] -quiet

# XDC: /home/duncan/QCS/QCS.gen/sources_1/bd/QCS_4/QCS_4_ooc.xdc

# XDC: /home/duncan/QCS/QCS.gen/sources_1/bd/QCS_4/QCS_4_ooc.xdc

# XDC: /home/duncan/QCS/QCS.gen/sources_1/bd/QCS_4_Top/QCS_4_Top_ooc.xdc
