# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/QCS_4_Top/ip/QCS_4_Top_ilmb_bram_if_cntlr_0/QCS_4_Top_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'QCS_4_Top_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/duncan/QCS/QCS.gen/sources_1/bd/QCS_4_Top/ip/QCS_4_Top_ilmb_bram_if_cntlr_0/QCS_4_Top_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'QCS_4_Top_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/QCS_4_Top/ip/QCS_4_Top_ilmb_bram_if_cntlr_0/QCS_4_Top_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'QCS_4_Top_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/duncan/QCS/QCS.gen/sources_1/bd/QCS_4_Top/ip/QCS_4_Top_ilmb_bram_if_cntlr_0/QCS_4_Top_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'QCS_4_Top_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
