# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/QCS_4_Top/ip/QCS_4_Top_QCS_4_wrapper_0_0/QCS_4_Top_QCS_4_wrapper_0_0.xci
# IP: The module: 'QCS_4_Top_QCS_4_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/duncan/QCS/QCS.srcs/sources_1/bd/QCS_4/QCS_4.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4 || ORIG_REF_NAME==QCS_4} -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/QCS_4/ip/QCS_4_rpm_lut_0_0/QCS_4_rpm_lut_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_rpm_lut_0_0 || ORIG_REF_NAME==QCS_4_rpm_lut_0_0} -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/QCS_4/ip/QCS_4_clk_cascade_0_0/QCS_4_clk_cascade_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_clk_cascade_0_0 || ORIG_REF_NAME==QCS_4_clk_cascade_0_0} -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/QCS_4/ip/QCS_4_addr_mux_0_0/QCS_4_addr_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_addr_mux_0_0 || ORIG_REF_NAME==QCS_4_addr_mux_0_0} -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/QCS_4/ip/QCS_4_QCS_no_lut_0_0/QCS_4_QCS_no_lut_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_QCS_no_lut_0_0 || ORIG_REF_NAME==QCS_4_QCS_no_lut_0_0} -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/QCS_4/ip/QCS_4_QCS_no_lut_1_0/QCS_4_QCS_no_lut_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_QCS_no_lut_1_0 || ORIG_REF_NAME==QCS_4_QCS_no_lut_1_0} -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/QCS_4/ip/QCS_4_QCS_no_lut_2_0/QCS_4_QCS_no_lut_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_QCS_no_lut_2_0 || ORIG_REF_NAME==QCS_4_QCS_no_lut_2_0} -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/QCS_4/ip/QCS_4_QCS_no_lut_3_0/QCS_4_QCS_no_lut_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_QCS_no_lut_3_0 || ORIG_REF_NAME==QCS_4_QCS_no_lut_3_0} -quiet] -quiet

# XDC: /home/duncan/QCS/QCS.gen/sources_1/bd/QCS_4/QCS_4_ooc.xdc

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/QCS_4_Top/ip/QCS_4_Top_QCS_4_wrapper_0_0/QCS_4_Top_QCS_4_wrapper_0_0.xci
# IP: The module: 'QCS_4_Top_QCS_4_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/duncan/QCS/QCS.srcs/sources_1/bd/QCS_4/QCS_4.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4 || ORIG_REF_NAME==QCS_4} -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/QCS_4/ip/QCS_4_rpm_lut_0_0/QCS_4_rpm_lut_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_rpm_lut_0_0 || ORIG_REF_NAME==QCS_4_rpm_lut_0_0} -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/QCS_4/ip/QCS_4_clk_cascade_0_0/QCS_4_clk_cascade_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_clk_cascade_0_0 || ORIG_REF_NAME==QCS_4_clk_cascade_0_0} -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/QCS_4/ip/QCS_4_addr_mux_0_0/QCS_4_addr_mux_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_addr_mux_0_0 || ORIG_REF_NAME==QCS_4_addr_mux_0_0} -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/QCS_4/ip/QCS_4_QCS_no_lut_0_0/QCS_4_QCS_no_lut_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_QCS_no_lut_0_0 || ORIG_REF_NAME==QCS_4_QCS_no_lut_0_0} -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/QCS_4/ip/QCS_4_QCS_no_lut_1_0/QCS_4_QCS_no_lut_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_QCS_no_lut_1_0 || ORIG_REF_NAME==QCS_4_QCS_no_lut_1_0} -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/QCS_4/ip/QCS_4_QCS_no_lut_2_0/QCS_4_QCS_no_lut_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_QCS_no_lut_2_0 || ORIG_REF_NAME==QCS_4_QCS_no_lut_2_0} -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/QCS_4/ip/QCS_4_QCS_no_lut_3_0/QCS_4_QCS_no_lut_3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_4_QCS_no_lut_3_0 || ORIG_REF_NAME==QCS_4_QCS_no_lut_3_0} -quiet] -quiet

# XDC: /home/duncan/QCS/QCS.gen/sources_1/bd/QCS_4/QCS_4_ooc.xdc
